# Generated by Django 3.2.12 on 2023-05-28 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pasien', '0004_pendaftaran_status_layanan'),
        ('kasir', '0002_initial'),
        ('poli', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoicePoliPasien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_harga', models.FloatField(default=0)),
                ('status_pembayaran', models.CharField(choices=[('Belum Bayar', 'Belum Bayar'), ('Sudah Bayar', 'Sudah Bayar')], default='Belum Bayar', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('poli', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='poli.poli')),
                ('resume_medis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pasien.resumemedis')),
                ('summary_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kasir.summaryinvoice')),
            ],
        ),
    ]
