# Generated by Django 4.2.5 on 2024-04-25 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("faskes", "0005_alter_faskes_user_alter_kantorcabang_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RegisterPostKlaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nomor_register",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "jenis_audit",
                    models.CharField(
                        choices=[
                            ("AAK-FKRTL", "AAK-FKRTL"),
                            ("VPK-FKRTL", "VPK-FKRTL"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Register", "Register"),
                            ("Verifikasi", "Verifikasi"),
                            ("Finalisasi", "Finalisasi"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "nomor_BA_VPK_AAK",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_final", models.BooleanField(default=False)),
                (
                    "inisiasi",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Hasil Verifikasi Pascaklaim", "Verifikasi Pascaklaim"),
                            (
                                "Hasil UR dan Deteksi Potensi Kecurangan",
                                "UR dan Deteksi Potensi Kecurangan",
                            ),
                            ("Whistle Blowing System", "Whistle Blowing System"),
                            ("Hasil Audit oleh Auditor", "Hasil Audit oleh Auditor"),
                            ("Hasil Audit Medis", "Hasil Audit Medis"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("periode_awal", models.DateField(blank=True, null=True)),
                ("periode_akhir", models.DateField(blank=True, null=True)),
                (
                    "surat_tugas",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("bulan_beban", models.DateField(blank=True, null=True)),
                (
                    "kelas",
                    models.CharField(
                        blank=True,
                        choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "faskes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faskes",
                        to="faskes.faskes",
                    ),
                ),
                (
                    "staff_upk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_upk",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verifikator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verifikator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SamplingDataKlaimCBG",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Nokapst", models.CharField(max_length=255)),
                ("Tgldtgsjp", models.DateField()),
                ("Tglplgsjp", models.DateField()),
                ("Nosjp", models.CharField(max_length=255)),
                ("Tglpelayanan", models.DateField()),
                ("Kdkrlayan", models.CharField(max_length=255)),
                ("Kdkclayan", models.CharField(max_length=255)),
                ("Nmkclayan", models.CharField(max_length=255)),
                ("Kddati2Layan", models.CharField(max_length=255)),
                ("Nmdati2Layan", models.CharField(max_length=255)),
                ("Kdppklayan", models.CharField(max_length=255)),
                ("Nmppklayan", models.CharField(max_length=255)),
                ("Nmtkp", models.CharField(max_length=255)),
                ("Kdinacbgs", models.CharField(max_length=255)),
                ("Nminacbgs", models.CharField(max_length=255)),
                ("Kddiagprimer", models.CharField(max_length=255)),
                ("Nmdiagprimer", models.CharField(max_length=255)),
                ("Diagsekunder", models.CharField(max_length=255)),
                ("Procedure", models.CharField(max_length=255)),
                ("Nmjnspulang", models.CharField(max_length=255)),
                ("kddokter", models.CharField(max_length=255)),
                ("nmdokter", models.CharField(max_length=255)),
                ("Umur", models.IntegerField()),
                ("kdsa", models.CharField(max_length=255)),
                ("kdsd", models.CharField(max_length=255)),
                ("deskripsisd", models.CharField(max_length=255)),
                ("kdsi", models.CharField(max_length=255)),
                ("deskripsisi", models.CharField(max_length=255)),
                ("kdsp", models.CharField(max_length=255)),
                ("deskripsisp", models.CharField(max_length=255)),
                ("kdsr", models.CharField(max_length=255)),
                ("deskripsisr", models.CharField(max_length=255)),
                ("Tarifgroup", models.IntegerField()),
                ("tarifsa", models.IntegerField()),
                ("tarifsd", models.IntegerField()),
                ("tarifsi", models.IntegerField()),
                ("tarifsp", models.IntegerField()),
                ("tarifsr", models.IntegerField()),
                ("Biayaverifikasi", models.IntegerField()),
                (
                    "Kdinacbgs_koreksi",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("biaya_koreksi", models.IntegerField(blank=True, null=True)),
                ("tgl_review", models.DateField(blank=True, null=True)),
                (
                    "keterangan_review",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("is_final", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "register",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vpkaak.registerpostklaim",
                    ),
                ),
                (
                    "verifikator_review",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
