# Generated by Django 4.2.5 on 2024-04-25 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vpkaak", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="samplingdataklaimcbg",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Belum Review", "Belum Review"),
                    ("Sesuai", "Sesuai"),
                    ("Tidak Sesuai", "Tidak Sesuai"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
