# Generated by Django 4.2.5 on 2024-04-26 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vpkaak', '0002_samplingdataklaimcbg_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registerpostklaim',
            old_name='nomor_register',
            new_name='nomor_register_klaim',
        ),
    ]
