# Generated by Django 4.2.5 on 2024-04-26 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpkaak', '0003_rename_nomor_register_registerpostklaim_nomor_register_klaim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerpostklaim',
            name='bulan_beban',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
