# Generated by Django 4.2.5 on 2024-04-26 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpkaak', '0004_alter_registerpostklaim_bulan_beban'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerpostklaim',
            name='bulan_beban',
            field=models.DateField(blank=True, null=True),
        ),
    ]
