# Generated by Django 4.2.5 on 2024-04-27 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vpkaak", "0005_alter_registerpostklaim_bulan_beban"),
    ]

    operations = [
        migrations.RemoveField(model_name="registerpostklaim", name="faskes",),
        migrations.RemoveField(model_name="registerpostklaim", name="kelas",),
        migrations.RemoveField(model_name="registerpostklaim", name="staff_upk",),
        migrations.RemoveField(model_name="registerpostklaim", name="verifikator",),
    ]
