# Generated by Django 4.2.5 on 2024-06-13 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vpkaak", "0006_remove_registerpostklaim_faskes_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="registerpostklaim",
            old_name="nomor_register_klaim",
            new_name="nomor_register",
        ),
        migrations.AlterField(
            model_name="registerpostklaim",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Register", "Register"),
                    ("Proses Review", "Proses Review"),
                    ("Selesai", "Selesai"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
