# Generated by Django 4.2.5 on 2024-04-27 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "vpkaak",
            "0007_rename_nomor_register_klaim_registerpostklaim_nomor_register_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="registerpostklaim",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_register",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
