# Generated by Django 4.2.5 on 2024-04-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vpkaak", "0008_registerpostklaim_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="samplingdataklaimcbg",
            name="Klsrawat",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
