# Generated by Django 4.2.5 on 2024-04-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vpkaak", "0010_alter_samplingdataklaimcbg_diagsekunder_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="samplingdataklaimcbg",
            name="status",
            field=models.CharField(
                choices=[
                    ("Belum Review", "Belum Review"),
                    ("Sesuai", "Sesuai"),
                    ("Tidak Sesuai", "Tidak Sesuai"),
                ],
                default="Belum Review",
                max_length=50,
            ),
        ),
    ]
