# Generated by Django 4.2.5 on 2024-04-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vpkaak", "0012_alter_samplingdataklaimcbg_diagsekunder_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="samplingdataklaimcbg",
            name="tgl_review",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
