# Generated by Django 4.2.5 on 2024-04-28 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vpkaak", "0013_alter_samplingdataklaimcbg_tgl_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="samplingdataklaimcbg",
            name="Klsrawat_koreksi",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
