# Generated by Django 4.2.5 on 2024-04-29 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vpkaak", "0015_registerpostklaim_tanggal_final"),
    ]

    operations = [
        migrations.AddField(
            model_name="registerpostklaim",
            name="tanggal_BA_VPK_AAK",
            field=models.DateField(blank=True, null=True),
        ),
    ]
