# Generated by Django 4.2.5 on 2024-04-29 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vpkaak", "0016_registerpostklaim_tanggal_ba_vpk_aak"),
    ]

    operations = [
        migrations.AddField(
            model_name="samplingdataklaimcbg",
            name="red_flag",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
