# Generated by Django 4.2.5 on 2024-04-29 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vpkaak", "0017_samplingdataklaimcbg_red_flag"),
    ]

    operations = [
        migrations.RenameField(
            model_name="samplingdataklaimcbg", old_name="red_flag", new_name="redflag",
        ),
    ]
