# Generated by Django 4.2.5 on 2024-05-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vpkaak", "0018_rename_red_flag_samplingdataklaimcbg_redflag"),
    ]

    operations = [
        migrations.AddField(
            model_name="registerpostklaim",
            name="biaya_efisiensi",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
