# Generated by Django 4.2.5 on 2024-06-04 03:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vpkaak", "0019_registerpostklaim_biaya_efisiensi"),
    ]

    operations = [
        migrations.AddField(
            model_name="registerpostklaim",
            name="is_kp",
            field=models.BooleanField(default=False),
        ),
    ]
