# Generated by Django 4.2.5 on 2024-06-05 07:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vpkaak", "0020_registerpostklaim_is_kp"),
    ]

    operations = [
        migrations.AddField(
            model_name="registerpostklaim",
            name="is_from_kp",
            field=models.BooleanField(default=False),
        ),
    ]
