# Generated by Django 4.2.5 on 2024-06-06 04:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vpkaak", "0021_registerpostklaim_is_from_kp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registerpostklaim",
            name="is_from_kp",
        ),
        migrations.AddField(
            model_name="samplingdataklaimcbg",
            name="is_from_kp",
            field=models.BooleanField(default=False),
        ),
    ]
