# Generated by Django 4.2.5 on 2024-06-18 02:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vpkaak", "0026_samplingdataklaimcbg_diagsekunder_koreksi_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="samplingdataklaimcbg",
            name="kddokter",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
