# Generated by Django 4.2.5 on 2024-06-18 02:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vpkaak", "0027_alter_samplingdataklaimcbg_kddokter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="samplingdataklaimcbg",
            name="nmdokter",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
