# Generated by Django 4.2.5 on 2024-06-19 10:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vpkaak", "0029_samplingdataklaimcbg_is_koreksi"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="samplingdataklaimcbg",
            name="is_koreksi",
        ),
    ]
