# Generated by Django 4.2.5 on 2024-06-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vpkaak", "0030_remove_samplingdataklaimcbg_is_koreksi"),
    ]

    operations = [
        migrations.AddField(
            model_name="samplingdataklaimcbg",
            name="is_koreksi",
            field=models.BooleanField(default=False),
        ),
    ]
