# Generated by Django 4.2.5 on 2024-06-23 17:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vpkaak", "0033_alter_samplingdataklaimcbg_kdkclayan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="samplingdataklaimcbg",
            name="Kdkclayan",
            field=models.CharField(
                max_length=255,
                validators=[django.core.validators.MinLengthValidator(4)],
            ),
        ),
    ]
