# Generated by Django 4.2.5 on 2024-07-02 07:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vpkaak", "0038_alter_samplingdataklaimcbg_keterangan_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="samplingdataklaimcbg",
            name="Nmtkp_koreksi",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
