# Generated by Django 4.2.5 on 2024-07-02 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vpkaak", "0039_samplingdataklaimcbg_nmtkp_koreksi"),
    ]

    operations = [
        migrations.AlterField(
            model_name="samplingdataklaimcbg",
            name="deskripsisp",
            field=models.CharField(default="-", max_length=255),
        ),
    ]
