# Generated by Django 4.2.5 on 2024-07-03 05:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vpkaak", "0041_alter_samplingdataklaimcbg_deskripsisd_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registerpostklaim",
            name="is_from_kp",
        ),
    ]
