# Generated by Django 4.2.5 on 2024-07-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vpkaak", "0043_cookiesicd"),
    ]

    operations = [
        migrations.AddField(
            model_name="samplingdataklaimcbg",
            name="deskripsi_redflag",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="samplingdataklaimcbg",
            name="source",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
