# Generated by Django 4.2.5 on 2024-07-22 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vpkaak", "0044_samplingdataklaimcbg_deskripsi_redflag_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="samplingdataklaimcbg",
            name="Kodersmenkes",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
