# Generated by Django 4.2.5 on 2024-09-01 02:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vpkaak", "0049_alter_samplingdataklaimcbg_jenis_fraud"),
    ]

    operations = [
        migrations.AlterField(
            model_name="samplingdataklaimcbg",
            name="is_status_koreksi_boa",
            field=models.CharField(default="Belum Koreksi BOA", max_length=255),
        ),
    ]
