# Generated by Django 4.2.5 on 2024-09-01 02:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vpkaak", "0050_alter_samplingdataklaimcbg_is_status_koreksi_boa"),
    ]

    operations = [
        migrations.RenameField(
            model_name="samplingdataklaimcbg",
            old_name="is_status_koreksi_boa",
            new_name="keterangan_koreksi_boa",
        ),
    ]
