# Generated by Django 4.2.5 on 2024-09-01 04:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vpkaak", "0052_samplingdataklaimcbg_status_koreksi_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="samplingdataklaimcbg",
            old_name="status_koreksi",
            new_name="status_koreksi_boa",
        ),
    ]
