# Generated by Django 4.2.5 on 2024-09-01 04:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "vpkaak",
            "0053_rename_status_koreksi_samplingdataklaimcbg_status_koreksi_boa",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="samplingdataklaimcbg",
            name="status_koreksi_boa",
            field=models.CharField(default="Belum Koreksi BOA", max_length=255),
        ),
    ]
