# Generated by Django 3.2.12 on 2023-05-29 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icd10',
            name='nama',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='icd9',
            name='nama',
            field=models.CharField(max_length=255),
        ),
    ]
