# Generated by Django 3.2.12 on 2023-05-26 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Karyawan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(blank=True, max_length=20, null=True)),
                ('nama_depan', models.CharField(max_length=255)),
                ('nama_belakang', models.CharField(blank=True, max_length=255, null=True)),
                ('nip', models.CharField(blank=True, max_length=20, null=True)),
                ('level', models.CharField(blank=True, max_length=50, null=True)),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-Laki'), ('P', 'Perempuan')], max_length=1)),
                ('tanggal_lahir', models.DateField(blank=True, null=True)),
                ('agama', models.CharField(blank=True, max_length=50, null=True)),
                ('no_kartu_keluarga', models.CharField(blank=True, max_length=20, null=True)),
                ('posisi_di_keluarga', models.CharField(blank=True, max_length=50, null=True)),
                ('pendidikan_terakhir', models.CharField(blank=True, max_length=255, null=True)),
                ('profesi', models.CharField(blank=True, max_length=255, null=True)),
                ('pekerjaan', models.CharField(blank=True, max_length=255, null=True)),
                ('no_npwp', models.CharField(blank=True, max_length=20, null=True)),
                ('sip', models.CharField(blank=True, max_length=20, null=True)),
                ('nama_ibu_kandung', models.CharField(blank=True, max_length=255, null=True)),
                ('golongan', models.CharField(blank=True, max_length=50, null=True)),
                ('pangkat', models.CharField(blank=True, max_length=50, null=True)),
                ('status_karyawan', models.CharField(blank=True, max_length=50, null=True)),
                ('unit_kerja', models.CharField(blank=True, max_length=255, null=True)),
                ('no_sk_pengangkatan', models.CharField(blank=True, max_length=20, null=True)),
                ('tanggal_sk_pengangkatan', models.DateField(blank=True, null=True)),
                ('tanggal_masuk_rs', models.DateField(blank=True, null=True)),
                ('no_telepon', models.CharField(blank=True, max_length=15, null=True)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('alamat_kelurahan', models.CharField(blank=True, max_length=255, null=True)),
                ('alamat_kecamatan', models.CharField(blank=True, max_length=255, null=True)),
                ('alamat_kabupaten_kota', models.CharField(blank=True, max_length=255, null=True)),
                ('alamat_provinsi', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Karyawan',
                'verbose_name_plural': 'Data Karyawan',
            },
        ),
    ]
