# Generated by Django 3.2.12 on 2023-05-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antrian', '0004_remove_antrian_resume_medis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antrian',
            name='task_id',
            field=models.FloatField(default=1),
        ),
    ]
