# Generated by Django 3.2.12 on 2023-05-26 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('antrian', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pasien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_rekam_medis', models.CharField(max_length=100, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('nik', models.CharField(max_length=100, unique=True)),
                ('tanggal_lahir', models.DateField()),
                ('status', models.CharField(choices=[('BARU', 'Baru'), ('LAMA', 'Lama')], max_length=30)),
                ('jenis_kelamin', models.CharField(choices=[('WANITA', 'Wanita'), ('PRIA', 'Pria')], max_length=30)),
                ('provinsi', models.CharField(max_length=100)),
                ('kabupaten', models.CharField(max_length=100)),
                ('kecamatan', models.CharField(max_length=100)),
                ('alamat', models.CharField(max_length=100)),
                ('agama', models.CharField(choices=[('Islam', 'Islam'), ('Kristen Protestan', 'kristen Protestan'), ('Kristen Katolik', 'Kristen Katolik'), ('Hindu', 'Hindu'), ('Buddha', 'Buddha'), ('Konghucu', 'Konghucu')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResumeMedis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_resume_medis', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pasien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pasien.pasien')),
            ],
        ),
        migrations.CreateModel(
            name='Pendaftaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asuransi', models.CharField(choices=[('UMUM', 'UMUM'), ('BPJS', 'BPJS')], default='UMUM', max_length=30)),
                ('kode_invoice', models.CharField(max_length=100)),
                ('no_peserta', models.CharField(blank=True, max_length=100, null=True)),
                ('tipe_layanan', models.CharField(blank=True, choices=[('IGD', 'IGD'), ('RAWAT_JALAN', 'Rawat Jalan')], max_length=50, null=True)),
                ('biaya', models.FloatField(default=0)),
                ('status_pembayaran', models.CharField(choices=[('Belum Bayar', 'Belum Bayar'), ('Sudah Bayar', 'Sudah Bayar')], default='Belum Bayar', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('antrian', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='antrian.antrian')),
            ],
        ),
    ]
