# Generated by Django 3.2.12 on 2023-05-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasien', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumemedis',
            name='cara_keluar',
            field=models.CharField(blank=True, choices=[('Dirujuk', 'Dirujuk'), ('Atas Persetujuan Dokter', 'Atas Persetujuan Dokter'), ('Atas Permintaan Sendiri', 'Atas Permintaan Sendiri'), ('Melarikan Diri', 'Melarikan Diri'), ('Meninggal', 'Meninggal'), ('Lainnya', 'Lainnya')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resumemedis',
            name='keadaan_keluar',
            field=models.CharField(blank=True, choices=[('Dirujuk Ke RS Lain', 'Dirujuk Ke RS Lain'), ('Sembuh', 'Sembuh'), ('Belum Sembuh', 'Belum Sembuh'), ('Meninggal Kurang 8 Jam', 'Meninggal Kurang 8 Jam'), ('Meninggal Lebih 8 Jam', 'Meninggal Kurang 8 Jam'), ('Meninggal Kurang 48 Jam', 'Meninggal Kurang 48 Jam'), ('Meninggal Lebih 48 Jam', 'Meninggal Lebih 48 Jam'), ('Diijinkan Pulang', 'Diijinkan Pulang')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resumemedis',
            name='no_rujukan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resumemedis',
            name='pemeriksaan_lanjut',
            field=models.CharField(blank=True, choices=[('Kontrol', 'Kontrol'), ('Bangsal', 'Bangsal'), ('Poliklinik RS', 'Poliklinik RS'), ('RS Lain', 'RS Lain'), ('Puskesmas', 'Puskesmas'), ('Lainnya', 'Lainnya')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resumemedis',
            name='rujukan',
            field=models.CharField(blank=True, choices=[('Fasekes 1', 'Fasekes 1'), ('Polisi', 'Polisi'), ('Sendiri', 'Sendiri'), ('Rumah Sakit', 'Rumah Sakit'), ('Puskesmas', 'Puskesmas'), ('Fasilitas Kesehatan Lain', 'Fasilitas Kesehatan Lain'), ('Dokter Keluarga', 'Dokter Keluarga')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pendaftaran',
            name='status_pembayaran',
            field=models.CharField(choices=[('Belum Bayar', 'Belum Bayar'), ('Sudah Bayar', 'Sudah Bayar'), ('Batal', 'Batal')], default='Belum Bayar', max_length=30),
        ),
    ]
