# Generated by Django 3.2.12 on 2023-05-28 04:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pasien', '0004_pendaftaran_status_layanan'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendaftaran',
            name='petugas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pendaftaran_petugas_admisi', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pendaftaran',
            name='dokter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pendaftaran_dokter', to=settings.AUTH_USER_MODEL),
        ),
    ]
