# Generated by Django 3.2.12 on 2023-05-28 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pasien', '0005_auto_20230528_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendaftaran',
            name='kode_invoice',
        ),
    ]
