# Generated by Django 3.2.12 on 2023-05-28 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otherlayanan', '0002_auto_20230527_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layananedukasipasien',
            name='kuantitas',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='layanankonsultasipasien',
            name='kuantitas',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='layananmonitoringpasien',
            name='kuantitas',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='layanantindakanpasien',
            name='kuantitas',
            field=models.IntegerField(default=1),
        ),
    ]
