# Generated by Django 3.2.12 on 2023-05-26 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('antrian', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetugasKasir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SummaryInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_invoice', models.CharField(max_length=100, unique=True)),
                ('resume_medis', models.CharField(blank=True, max_length=100, null=True)),
                ('status_pembayaran', models.CharField(choices=[('Belum Bayar', 'Belum Bayar'), ('Sudah Bayar', 'Sudah Bayar')], default='Belum Bayar', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('antrian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='antrian.antrian')),
            ],
        ),
    ]
