# Generated by Django 3.2.12 on 2023-05-28 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasir', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='summaryinvoice',
            name='totals',
            field=models.FloatField(default=0),
        ),
    ]
