# Generated by Django 3.2.12 on 2023-05-26 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pasien', '0002_initial'),
        ('icd', '0001_initial'),
        ('antrian', '0002_initial'),
        ('soap', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmenticd9',
            name='dokter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='icd9_dokter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessmenticd9',
            name='icd9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='icd.icd9'),
        ),
        migrations.AddField(
            model_name='assessmenticd9',
            name='perawat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='icd9_perawat', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessmenticd9',
            name='resume_medis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pasien.resumemedis'),
        ),
        migrations.AddField(
            model_name='assessmenticd10',
            name='antrian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='antrian.antrian'),
        ),
        migrations.AddField(
            model_name='assessmenticd10',
            name='dokter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='icdx_dokter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessmenticd10',
            name='icd10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='icd.icd10'),
        ),
        migrations.AddField(
            model_name='assessmenticd10',
            name='perawat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='icdx_perawat', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessmenticd10',
            name='resume_medis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pasien.resumemedis'),
        ),
    ]
