# Generated by Django 3.2.12 on 2023-05-26 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kasir', '0002_initial'),
        ('radiologi', '0001_initial'),
        ('pasien', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='layananradiologipasien',
            name='dokter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='radiologi_dokter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='layananradiologipasien',
            name='layanan_radiologi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='radiologi.layananradiologi'),
        ),
        migrations.AddField(
            model_name='layananradiologipasien',
            name='petugas_radiologi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='radiologi_petugas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='layananradiologipasien',
            name='resume_medis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pasien.resumemedis'),
        ),
        migrations.AddField(
            model_name='layananradiologipasien',
            name='summary_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kasir.summaryinvoice'),
        ),
        migrations.AddField(
            model_name='layananradiologi',
            name='kateori',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='radiologi.kategorilayananradiologi'),
        ),
        migrations.AddField(
            model_name='filetracer',
            name='layanan_radiologi_pasien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='radiologi.layananradiologipasien'),
        ),
    ]
