# Generated by Django 3.2.12 on 2023-05-27 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiologi', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='layananradiologipasien',
            name='diagnosa',
            field=models.TextField(blank=True, null=True),
        ),
    ]
