# Generated by Django 3.2.12 on 2023-05-27 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiologi', '0004_remove_layananradiologipasien_deskripsi'),
    ]

    operations = [
        migrations.AddField(
            model_name='layananradiologipasien',
            name='catatan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
