# Generated by Django 3.2.12 on 2023-05-26 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmasi', '0001_initial'),
        ('antrian', '0002_initial'),
        ('pasien', '0001_initial'),
        ('kasir', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='petugasfarmasi',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='obatpasien',
            name='antrian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='antrian.antrian'),
        ),
        migrations.AddField(
            model_name='obatpasien',
            name='dokter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farmasi_dokter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='obatpasien',
            name='obat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farmasi.obat'),
        ),
        migrations.AddField(
            model_name='obatpasien',
            name='petugas_farmasi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farmasi_petugas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='obatpasien',
            name='resume_medis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pasien.resumemedis'),
        ),
        migrations.AddField(
            model_name='obatpasien',
            name='summary_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kasir.summaryinvoice'),
        ),
    ]
