# Generated by Django 3.2.12 on 2023-05-27 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmasi', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='obatpasien',
            name='deskripsi',
            field=models.TextField(blank=True, null=True),
        ),
    ]
