# Generated by Django 3.2.12 on 2023-05-27 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmasi', '0003_obatpasien_deskripsi'),
    ]

    operations = [
        migrations.AddField(
            model_name='obatpasien',
            name='status_layanan',
            field=models.CharField(choices=[('Menunggu', 'Menunggu'), ('Dilayani', 'Dilayani'), ('Selesai', 'Selesai'), ('Batal', 'Batal')], default='Menunggu', max_length=30),
        ),
    ]
