# Generated by Django 3.2.12 on 2023-05-30 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmasi', '0005_auto_20230530_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obat',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20),
        ),
    ]
