# Generated by Django 3.2.12 on 2023-05-30 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmasi', '0007_rename_hna_ppn_obat_ppn'),
    ]

    operations = [
        migrations.AddField(
            model_name='obat',
            name='harga',
            field=models.FloatField(default=0),
        ),
    ]
