# Generated by Django 3.2.12 on 2023-05-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmasi', '0008_obat_harga'),
    ]

    operations = [
        migrations.AddField(
            model_name='obat',
            name='stok',
            field=models.FloatField(default=0),
        ),
    ]
