# Generated by Django 3.2.12 on 2023-05-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmasi', '0009_obat_stok'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obat',
            name='stok',
            field=models.IntegerField(default=0),
        ),
    ]
