# Generated by Django 3.2.12 on 2023-05-30 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmasi', '0010_alter_obat_stok'),
    ]

    operations = [
        migrations.AddField(
            model_name='obatpasien',
            name='keterangan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
