# Generated by Django 4.2.5 on 2024-09-04 01:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DataKlaimCBGMetafisik",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "no_surat_bast",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("tgl_bast", models.DateField(blank=True, null=True)),
                ("nokapst", models.CharField(blank=True, max_length=50, null=True)),
                ("tgldtgsep", models.DateField(blank=True, null=True)),
                ("tglplgsep", models.DateField(blank=True, null=True)),
                ("nosjp", models.CharField(blank=True, max_length=50, null=True)),
                ("tgl_pelayanan", models.DateField(blank=True, null=True)),
                ("kdkrlayan", models.CharField(blank=True, max_length=10, null=True)),
                ("kdkclayan", models.CharField(blank=True, max_length=10, null=True)),
                ("kdppklayan", models.CharField(blank=True, max_length=20, null=True)),
                ("nmppklayan", models.CharField(blank=True, max_length=255, null=True)),
                ("nmtkp", models.CharField(blank=True, max_length=255, null=True)),
                ("kdinacbgs", models.CharField(blank=True, max_length=10, null=True)),
                ("nminacbgs", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "kddiagprimer",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "nmdiagprimer",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "diagsekunder",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("prosedur", models.CharField(blank=True, max_length=1000, null=True)),
                ("klsrawat", models.CharField(blank=True, max_length=10, null=True)),
                ("nmjnspulang", models.CharField(blank=True, max_length=50, null=True)),
                ("kddokter", models.CharField(blank=True, max_length=10, null=True)),
                ("nmdokter", models.CharField(blank=True, max_length=255, null=True)),
                ("umur_tahun", models.IntegerField(blank=True, null=True)),
                ("kdsa", models.CharField(blank=True, max_length=10, null=True)),
                ("kdsd", models.CharField(blank=True, max_length=10, null=True)),
                ("deskripsisd", models.CharField(blank=True, max_length=50, null=True)),
                ("kdsi", models.CharField(blank=True, max_length=10, null=True)),
                ("kdsp", models.CharField(blank=True, max_length=10, null=True)),
                ("deskripsisp", models.CharField(blank=True, max_length=50, null=True)),
                ("kdsr", models.CharField(blank=True, max_length=10, null=True)),
                ("deskripsisr", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "tarifsa",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "tarifsd",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "tarifsi",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "tarifsp",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "tarifsr",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "biayars",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
            ],
        ),
    ]
