# Generated by Django 4.2.5 on 2024-09-05 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("metafisik", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NoBAMetafisik",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "no_surat_bast",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("tgl_bast", models.DateField(blank=True, null=True)),
                ("tgl_pelayanan", models.DateField(blank=True, null=True)),
                ("total_klaim", models.IntegerField(blank=True, null=True)),
                ("total_redflag", models.IntegerField(blank=True, null=True)),
                ("total_layak", models.IntegerField(blank=True, null=True)),
                ("total_pending", models.IntegerField(blank=True, null=True)),
                ("total_tidaklayak", models.IntegerField(blank=True, null=True)),
                ("kdkrlayan", models.CharField(blank=True, max_length=10, null=True)),
                ("kdkclayan", models.CharField(blank=True, max_length=10, null=True)),
                ("kdppklayan", models.CharField(blank=True, max_length=20, null=True)),
                ("nmppklayan", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="dataklaimcbgmetafisik",
            name="kdkclayan",
        ),
        migrations.RemoveField(
            model_name="dataklaimcbgmetafisik",
            name="kdkrlayan",
        ),
        migrations.RemoveField(
            model_name="dataklaimcbgmetafisik",
            name="kdppklayan",
        ),
        migrations.RemoveField(
            model_name="dataklaimcbgmetafisik",
            name="nmppklayan",
        ),
        migrations.RemoveField(
            model_name="dataklaimcbgmetafisik",
            name="no_surat_bast",
        ),
        migrations.RemoveField(
            model_name="dataklaimcbgmetafisik",
            name="tgl_bast",
        ),
        migrations.RemoveField(
            model_name="dataklaimcbgmetafisik",
            name="tgl_pelayanan",
        ),
        migrations.AddField(
            model_name="dataklaimcbgmetafisik",
            name="no_bast",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="metafisik.nobametafisik",
            ),
        ),
    ]
