# Generated by Django 4.2.5 on 2024-09-05 08:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        (
            "metafisik",
            "0002_nobametafisik_remove_dataklaimcbgmetafisik_kdkclayan_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="dataklaimcbgmetafisik",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dataklaimcbgmetafisik",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="nobametafisik",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="nobametafisik",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
