# Generated by Django 4.2.5 on 2024-09-09 06:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metafisik", "0004_alter_nobametafisik_no_surat_bast"),
    ]

    operations = [
        migrations.AddField(
            model_name="nobametafisik",
            name="is_import",
            field=models.BooleanField(default=False),
        ),
    ]
