# Generated by Django 4.2.5 on 2024-09-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metafisik", "0005_nobametafisik_is_import"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataklaimcbgmetafisik",
            name="diagsekunder",
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name="dataklaimcbgmetafisik",
            name="prosedur",
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
