# Generated by Django 4.2.5 on 2024-09-09 08:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metafisik", "0006_alter_dataklaimcbgmetafisik_diagsekunder_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataklaimcbgmetafisik",
            name="kdsa",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="dataklaimcbgmetafisik",
            name="kdsd",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="dataklaimcbgmetafisik",
            name="kdsi",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="dataklaimcbgmetafisik",
            name="kdsp",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="dataklaimcbgmetafisik",
            name="kdsr",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
