# Generated by Django 4.2.5 on 2024-09-13 07:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metafisik", "0007_alter_dataklaimcbgmetafisik_kdsa_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dataklaimcbgmetafisik",
            old_name="biayars",
            new_name="bytagsep",
        ),
        migrations.AddField(
            model_name="dataklaimcbgmetafisik",
            name="tarifgroup",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
