# Generated by Django 4.2.5 on 2024-09-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metafisik", "0009_nobametafisik_is_bagi"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataklaimcbgmetafisik",
            name="politusjp",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
