# Generated by Django 4.2.5 on 2024-09-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metafisik", "0010_dataklaimcbgmetafisik_politusjp"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataklaimcbgmetafisik",
            name="deskripsi_redflag",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="dataklaimcbgmetafisik",
            name="indikator_redflag",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="dataklaimcbgmetafisik",
            name="redflag",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
