# Generated by Django 4.2.5 on 2024-09-16 03:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("metafisik", "0011_dataklaimcbgmetafisik_deskripsi_redflag_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dataklaimcbgmetafisik",
            old_name="politusjp",
            new_name="politujsep",
        ),
    ]
