# Generated by Django 4.2.5 on 2024-09-16 03:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "metafisik",
            "0013_rename_indikator_redflag_dataklaimcbgmetafisik_id_logik_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="dataklaimcbgmetafisik",
            name="biayars",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
