# Generated by Django 4.2.5 on 2024-09-16 14:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("metafisik", "0014_dataklaimcbgmetafisik_biayars"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dataklaimcbgmetafisik",
            old_name="tarifgroup",
            new_name="tarifgrup",
        ),
    ]
