# Generated by Django 4.2.2 on 2023-07-23 23:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("verifikator", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="hitungdataklaim", name="jenis_klaim",),
        migrations.AddField(
            model_name="hitungdataklaim",
            name="jamhitung",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="hitungdataklaim",
            name="nomor_register_klaim",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="hitungdataklaim",
            name="tglhitung",
            field=models.DateField(auto_now_add=True),
        ),
    ]
