# Generated by Django 4.2.2 on 2023-07-24 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("verifikator", "0003_hitungdataklaim_jenis_klaim_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hitungdataklaim",
            name="periodehitung",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
