# Generated by Django 4.2.2 on 2023-07-24 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("verifikator", "0004_alter_hitungdataklaim_periodehitung"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hitungdataklaim",
            name="jamhitung",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hitungdataklaim",
            name="tglhitung",
            field=models.DateField(blank=True, null=True),
        ),
    ]
