# Generated by Django 4.2.5 on 2023-09-21 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_user_user_agent_delete_userprofile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user", old_name="user_agent", new_name="meta",
        ),
    ]
