# Generated by Django 4.2.5 on 2023-09-27 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0008_rename_user_agent_user_meta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
