# Generated by Django 4.2.5 on 2023-10-25 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0012_alter_user_first_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="npp",
            field=models.CharField(default="NPP Kosong", max_length=25),
        ),
    ]
