# Generated by Django 3.2.12 on 2023-05-26 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('antrian', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HasilSubLayananLab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hasil', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='KategoriLayananLab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LayananLab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('harga', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubLayananLab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('hasil_normal', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('layanan_lab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab.layananlab')),
            ],
        ),
        migrations.CreateModel(
            name='LayananLabPasien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harga', models.FloatField(default=0)),
                ('kuantitas', models.IntegerField(default=1)),
                ('total_harga', models.FloatField(default=0)),
                ('status_pembayaran', models.CharField(choices=[('Belum Bayar', 'Belum Bayar'), ('Sudah Bayar', 'Sudah Bayar')], default='Belum Bayar', max_length=30)),
                ('status_layanan', models.CharField(choices=[('Menunggu', 'Menunggu'), ('Dilayani', 'Dilayani'), ('Selesai', 'Selesai'), ('Batal', 'Batal')], default='Menunggu', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('antrian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='antrian.antrian')),
            ],
        ),
    ]
