# Generated by Django 3.2.12 on 2023-05-27 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_layananlabpasien_diagnosa'),
    ]

    operations = [
        migrations.AddField(
            model_name='layananlabpasien',
            name='catatan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
