# Generated by Django 3.2.12 on 2023-05-28 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0004_layananlabpasien_catatan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kategorilayananlab',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
