# Generated by Django 4.2.2 on 2023-06-28 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faskes', '0005_alter_faskes_user_alter_kantorcabang_user'),
        ('klaim', '0003_alter_registerklaim_verifikator'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registerklaim',
            unique_together={('faskes', 'bulan_pelayanan')},
        ),
    ]
