# Generated by Django 4.2.2 on 2023-06-28 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('faskes', '0005_alter_faskes_user_alter_kantorcabang_user'),
        ('klaim', '0004_alter_registerklaim_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataKlaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bupel', models.DateField(blank=True, null=True)),
                ('tgl_SLA', models.DateField(blank=True, null=True)),
                ('Algoritma', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(choices=[('Pembahasan', 'Pembahasan'), ('Tidak Layak', 'Tidak Layak'), ('Layak', 'Layak'), ('Pending', 'Pending'), ('Dispute', 'Dispute'), ('Klaim', 'Klaim'), ('Belum Ver', 'Belum Ver'), ('Proses', 'Proses')], default='Belum Ver', max_length=200)),
                ('NOSEP', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('TGLSEP', models.DateField(blank=True, null=True)),
                ('TGLPULANG', models.DateField(blank=True, null=True)),
                ('JNSPEL', models.CharField(blank=True, choices=[('Rawat Inap', 'Rawat Inap'), ('Rawat Jalan', 'Rawat Jalan')], max_length=200, null=True)),
                ('NOKARTU', models.CharField(blank=True, max_length=200, null=True)),
                ('NMPESERTA', models.CharField(blank=True, max_length=200, null=True)),
                ('POLI', models.CharField(blank=True, max_length=200, null=True)),
                ('KDINACBG', models.CharField(blank=True, max_length=200, null=True)),
                ('BYPENGAJUAN', models.IntegerField(default=0)),
                ('ket_pending', models.CharField(blank=True, max_length=500, null=True)),
                ('ket_jawaban_pending', models.CharField(blank=True, max_length=500, null=True)),
                ('prosesklaim', models.BooleanField(default=False)),
                ('prosespending', models.BooleanField(default=False)),
                ('prosesdispute', models.BooleanField(default=False)),
                ('file_konfirmasi', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('jenis_dispute', models.CharField(blank=True, choices=[('Medis', 'Medis'), ('Koding', 'Koding'), ('Obat', 'Obat'), ('COB', 'COB')], max_length=200, null=True)),
                ('klasifikasi_dispute', models.CharField(blank=True, max_length=200, null=True)),
                ('keterangan_dispute', models.CharField(blank=True, max_length=500, null=True)),
                ('proses_klasifikasi_dispute', models.BooleanField(default=False)),
                ('hitung', models.PositiveIntegerField(default=0)),
                ('tglhitung', models.DateField(blank=True, null=True)),
                ('flaghitung', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faskes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faskes.faskes')),
                ('register_klaim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klaim.registerklaim')),
                ('verifikator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
