# Generated by Django 4.2.2 on 2023-06-29 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klaim', '0005_dataklaim'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerklaim',
            name='has_import_data',
            field=models.BooleanField(default=False),
        ),
    ]
