# Generated by Django 4.2.2 on 2023-07-01 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klaim', '0006_registerklaim_has_import_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerklaim',
            name='has_import_data',
        ),
        migrations.AddField(
            model_name='registerklaim',
            name='file_data_klaim',
            field=models.FileField(blank=True, null=True, upload_to='data-klaim/'),
        ),
    ]
