# Generated by Django 4.2.2 on 2023-07-02 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("klaim", "0007_remove_registerklaim_has_import_data_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registerklaim",
            name="nomor_surat_pengajuan_rs",
            field=models.CharField(max_length=50),
        ),
    ]
