# Generated by Django 4.2.2 on 2023-07-02 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("klaim", "0008_alter_registerklaim_nomor_surat_pengajuan_rs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jenisklaim",
            name="nama",
            field=models.CharField(
                choices=[
                    ("CBG-Reguler", "CBG-Reguler"),
                    ("CBG-Pending", "CBG-Pending"),
                    ("Obat-Reguler", "Obat-Reguler"),
                    ("Obat-Pending", "Obat-Pending"),
                    ("Optik", "Optik"),
                    ("CAPD", "CAPD"),
                    ("Ambulance-FKRTL", "Ambulance-FKRTL"),
                    ("Alkes", "Alkes"),
                ],
                max_length=250,
                unique=True,
            ),
        ),
    ]
