# Generated by Django 4.2.2 on 2023-07-02 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("klaim", "0011_alter_jenisklaim_nama"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="registerklaim", unique_together=set(),),
    ]
