# Generated by Django 4.2.2 on 2023-07-02 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("klaim", "0012_alter_registerklaim_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registerklaim",
            name="tgl_aju",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
