# Generated by Django 4.2.2 on 2023-07-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("klaim", "0014_alter_registerklaim_tgl_ba_lengkap_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registerklaim",
            name="tgl_ba_lengkap",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="registerklaim",
            name="tgl_ba_verif",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="registerklaim",
            name="tgl_terima",
            field=models.DateField(blank=True, null=True),
        ),
    ]
