# Generated by Django 4.2.2 on 2023-07-08 08:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("faskes", "0005_alter_faskes_user_alter_kantorcabang_user"),
        ("klaim", "0016_registerklaim_is_final"),
    ]

    operations = [
        migrations.RenameModel(old_name="DataKlaim", new_name="DataKlaimCBG",),
    ]
