# Generated by Django 4.2.2 on 2023-07-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("klaim", "0018_dataklaimcbg_register"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataklaimcbg",
            name="register",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
