# Generated by Django 4.2.2 on 2023-07-08 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("klaim", "0019_alter_dataklaimcbg_register"),
    ]

    operations = [
        migrations.RemoveField(model_name="dataklaimcbg", name="register",),
    ]
