# Generated by Django 4.2.2 on 2023-07-11 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("klaim", "0020_remove_dataklaimcbg_register"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dataklaimcbg",
            old_name="ket_pending",
            new_name="ket_pending_dispute",
        ),
    ]
