# Generated by Django 4.2.2 on 2023-08-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("klaim", "0023_remove_dataklaimcbg_hitung_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataklaimcbg",
            name="jenis_pending",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Kelengkapan Administrasi", "Kelengkapan Administrasi"),
                    ("Kaidah Koding", "Kaidah Koding"),
                    ("Standar Pelayanan", "Standar Pelayanan"),
                ],
                max_length=200,
                null=True,
            ),
        ),
    ]
