# Generated by Django 4.2.2 on 2023-08-18 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("klaim", "0024_dataklaimcbg_jenis_pending"),
    ]

    operations = [
        migrations.CreateModel(
            name="JawabanPendingDispute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ket_jawaban_pending", models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="KeteranganPendingDispute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ket_pending_dispute", models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(model_name="dataklaimcbg", name="ket_jawaban_pending",),
        migrations.RemoveField(model_name="dataklaimcbg", name="ket_pending_dispute",),
        migrations.AddField(
            model_name="dataklaimcbg",
            name="ket_jawaban_pending",
            field=models.ManyToManyField(
                blank=True, null=True, to="klaim.jawabanpendingdispute"
            ),
        ),
        migrations.AddField(
            model_name="dataklaimcbg",
            name="ket_pending_dispute",
            field=models.ManyToManyField(
                blank=True, null=True, to="klaim.keteranganpendingdispute"
            ),
        ),
    ]
