# Generated by Django 4.2.2 on 2023-08-18 06:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("klaim", "0025_jawabanpendingdispute_keteranganpendingdispute_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jawabanpendingdispute",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="jawabanpendingdispute",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="keteranganpendingdispute",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="keteranganpendingdispute",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
