# Generated by Django 4.2.2 on 2023-08-19 04:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("klaim", "0028_keteranganpendingdispute_verifikator"),
    ]

    operations = [
        migrations.AddField(
            model_name="jawabanpendingdispute",
            name="user_faskes",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
