# Generated by Django 4.2.2 on 2023-08-19 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klaim', '0029_jawabanpendingdispute_user_faskes'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerklaim',
            name='is_pengajuan_ulang',
            field=models.BooleanField(default=False),
        ),
    ]
