# Generated by Django 4.2.2 on 2023-08-22 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("klaim", "0031_dataklaimcbg_register_klaim_bayangan"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dataklaimcbg",
            old_name="register_klaim_bayangan",
            new_name="data_klaim_self",
        ),
    ]
