# Generated by Django 4.2.2 on 2023-08-23 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("klaim", "0032_rename_register_klaim_bayangan_dataklaimcbg_data_klaim_self"),
    ]

    operations = [
        migrations.RemoveField(model_name="dataklaimcbg", name="data_klaim_self",),
    ]
