# Generated by Django 4.2.5 on 2023-09-10 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("klaim", "0033_remove_dataklaimcbg_data_klaim_self"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataklaimcbg",
            name="BYPENGAJUAN",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="registerklaim",
            name="biaya_rawat_inap_aju",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="registerklaim",
            name="biaya_rawat_jalan_aju",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="registerklaim",
            name="kasus_rawat_inap_aju",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="registerklaim",
            name="kasus_rawat_jalan_aju",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
