# Generated by Django 4.2.5 on 2023-10-18 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("klaim", "0037_remove_registerklaim_password_file_excel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataklaimcbg",
            name="Algoritma",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
