# Generated by Django 4.2.5 on 2023-11-03 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("klaim", "0039_rename_algoritma_dataklaimcbg_algoritma"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataklaimcbg",
            name="prosestidaklayak",
            field=models.BooleanField(default=False),
        ),
    ]
