# Generated by Django 4.2.5 on 2023-11-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("klaim", "0040_dataklaimcbg_prosestidaklayak"),
    ]

    operations = [
        migrations.CreateModel(
            name="SLAVerifikasiDataKlaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sla_cbg", models.PositiveBigIntegerField(default=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
