# Generated by Django 4.2.5 on 2023-11-03 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("klaim", "0041_slaverifikasidataklaim"),
    ]

    operations = [
        migrations.DeleteModel(name="SLAVerifikasiDataKlaim",),
        migrations.AddField(
            model_name="jenisklaim",
            name="plus_hari_sla",
            field=models.PositiveBigIntegerField(default=6),
        ),
    ]
