# Generated by Django 4.2.5 on 2023-11-03 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("faskes", "0005_alter_faskes_user_alter_kantorcabang_user"),
        ("klaim", "0042_delete_slaverifikasidataklaim_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="jenisklaim", name="plus_hari_sla",),
        migrations.AddField(
            model_name="jenisklaim",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="SLA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plus_hari_sla", models.PositiveIntegerField(default=6)),
                (
                    "jenis_klaim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="klaim.jenisklaim",
                    ),
                ),
                (
                    "kantor_cabang",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="faskes.kantorcabang",
                    ),
                ),
            ],
        ),
    ]
