# Generated by Django 4.2.5 on 2023-11-04 00:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("klaim", "0043_remove_jenisklaim_plus_hari_sla_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sla",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sla",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
