# Generated by Django 4.2.5 on 2023-12-05 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("klaim", "0051_dataklaimobat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataklaimobat",
            name="KdJenis",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name="dataklaimobat",
            name="NoKartu",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="dataklaimobat",
            name="NoResep",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="dataklaimobat",
            name="NoSEPApotek",
            field=models.CharField(blank=True, max_length=19, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="dataklaimobat",
            name="NoSEPAsalResep",
            field=models.CharField(blank=True, max_length=19, null=True),
        ),
        migrations.AlterField(
            model_name="dataklaimobat",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pembahasan", "Pembahasan"),
                    ("Tidak Layak", "Tidak Layak"),
                    ("Layak", "Layak"),
                    ("Pending", "Pending"),
                    ("Dispute", "Dispute"),
                    ("Klaim", "Klaim"),
                    ("Belum Ver", "Belum Ver"),
                    ("Proses", "Proses"),
                ],
                default="Belum Ver",
                max_length=20,
            ),
        ),
    ]
