# Generated by Django 4.2.5 on 2024-02-04 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("klaim", "0052_alter_dataklaimobat_kdjenis_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jawabanpendingdispute",
            name="ket_jawaban_pending",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="keteranganpendingdispute",
            name="ket_pending_dispute",
            field=models.CharField(max_length=1000),
        ),
    ]
