# Generated by Django 4.2.5 on 2024-02-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("klaim", "0054_registerklaim_is_potongklaim_registerklaim_prosesboa"),
    ]

    operations = [
        migrations.AddField(
            model_name="registerklaim",
            name="tgl_boa",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="registerklaim",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pengajuan", "Pengajuan"),
                    ("Terima", "Terima"),
                    ("Verifikasi", "Verifikasi"),
                    ("Selesai", "Selesai"),
                    ("Dikembalikan", "Dikembalikan"),
                ],
                default="Pengajuan",
                max_length=50,
            ),
        ),
    ]
