# Generated by Django 4.2.5 on 2024-02-06 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("klaim", "0055_registerklaim_tgl_boa_alter_registerklaim_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="registerklaim",
            name="keterangan_potongklaim",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
