# Generated by Django 4.2.5 on 2024-09-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("klaim", "0060_alter_dataklaimcbg_status_sinkron_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataklaimcbg",
            name="deskripsi_metafisik",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="dataklaimcbg",
            name="is_metafisik",
            field=models.BooleanField(default=False),
        ),
    ]
