# Generated by Django 4.2.5 on 2024-09-14 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("klaim", "0061_dataklaimcbg_deskripsi_metafisik_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataklaimcbg",
            name="indikator_metafisik",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
