# Generated by Django 4.2.2 on 2023-06-27 01:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('faskes', '0003_faskes_user_kantorcabang_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kepwil',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
